### PR TITLE
Update permissions to latest Supervisor

### LINKED ISSUE #9: Deprecated add-on config
Hi! I see this warning in my logs:
```log
21-02-09 08:59:56 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of HDD Tools
21-02-09 08:59:56 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of HDD Tools
```

The add-on is working, but I suppose it will fail at some version in the future.

### LINKED ISSUE #12: Addon has stopped working with supervisor update to 2021.02.11
It looks like this issue is connected with "deprecated add-on config":
https://github.com/Draggon/hassio-hdd-tools/issues/9

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Fri Feb 19 21:28:24 CET 2021][Info] HDD Tools start
[Fri Feb 19 21:28:24 CET 2021][Info] Configuration - performance check enabled: false
[Fri Feb 19 21:28:24 CET 2021][Info] Configuration - disk path: /dev/sda
[Fri Feb 19 21:28:24 CET 2021][Info] Configuration - check period: 1
[Fri Feb 19 21:28:24 CET 2021][Info] Configuration - output file: temp.log
[Fri Feb 19 21:28:24 CET 2021][Info] Configuration - attributes property: ata_smart_attributes.table
[Fri Feb 19 21:28:24 CET 2021][Info] Init run
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): null (null) has no keys
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.attributes +=               
jq: 1 compile error
[Fri Feb 19 21:28:25 CET 2021][INFO] Sensor value: null°
[Fri Feb 19 21:28:25 CET 2021][DEBUG] Sensor data which would be pushed to home-assistant and exposed as "sensor.hdd_temp": 
[Fri Feb 19 21:28:25 CET 2021][DEBUG] debug is enabled, sensor data is not published to home-assistant!
[Fri Feb 19 21:28:25 CET 2021][Info] Cron tab update
[Fri Feb 19 21:28:25 CET 2021][Info] Apply cron tab
[Fri Feb 19 21:28:25 CET 2021][Info] Device /dev/sda found - staring CRON
```

## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.94
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3792
Installed Version | 1.11.3
Stage | running
Available Repositories | 815
Installed Repositories | 67

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 49

</details>

<details><summary>Airly</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.11
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.11
docker_version | 19.03.13
disk_total | 219.4 GB
disk_used | 27.9 GB
healthy | true
supported | true
board | intel-nuc
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.103.1), Log Viewer (0.9.1), Check Home Assistant configuration (3.6.0), chrony (2.0.0), Samba share (9.3.0), Terminal & SSH (9.0.1), motionEye (0.11.0), AppDaemon 3 (5.0.1), ESPHome (1.16.1), Example (4.0.4), Node-RED (8.1.1), Bitwarden RS (0.8.0), ESPHome (dev) (dev), Glances (0.11.1), Grocy (0.11.0), Folding@home (0.2.0), File editor (5.2.0), Spotify Connect (0.8.2), Portainer (1.4.0), ZeroTier One (0.10.3), Mosquitto broker (5.1), ADB - Android Debug Bridge (0.7.0), FTP (4.0.1), SSH & Web Terminal (8.0.2), Local VLC (18), HDD Tools (0.46)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 36
views | 19
mode | storage

</details>

### PR DESCRIPTION
**Pull request by McGiverGim**
Seems to fix https://github.com/Draggon/hassio-hdd-tools/issues/12 and fix https://github.com/Draggon/hassio-hdd-tools/issues/9

What I don't know is what will happen with people with "old" versions of Home Assistant, I can't find when this configuration was changed and since when is mandatory some of them. We can add a "homeassistant" tag too with the minimum version, but I don't know what will be the correct version to limit.

Another doubt: I've configured the addon with `startup: "application"` because the data can't be sent to HA until this has started, but maybe for some reason it was configured to start before (maybe because the speed test that is optional?). The options are:

> Default `application`. `initialize` will start add-on on setup of Home Assistant. `system` is for things like databases and not dependent on other things. `services` will start before Home Assistant, while `application` is started afterwards. Finally `once` is for applications that don't run as a daemon.

Other testing is welcome to be sure I've not broken anything.

Another benefit of this changes is that the "full access" is not needed anymore in HA. At least in my tests it seems to work now without it.

### CODE REVIEW

**Comment by McGiverGim** [comment]
Looking at this again, maybe without `full access` we can't access devices if they are at a different mount point than `/dev/sda`.

**Comment by SPEC1AL1ST** [comment]
> Looking at this again, maybe without `full access` we can't access devices if they are at a different mount point than `/dev/sda`.

Maybe you can fork and fix this git? If you know how.

**Comment by McGiverGim** [comment]
@SPEC1AL1ST I'm not too sure what are the final "needed" changes. With this changes it works in my system. I have my repo containing the changes of this PR in a temporary way (until merged in this official repo).

If you want, please test my repo: https://github.com/McGiverGim/hassio-hdd-tools

If it works, perfect, if not we can try to find a fix for your system.

**Comment by boesing** [comment]
Can confirm that this works for me on 2021.3.0

**Review by Draggon — APPROVED** [review]

**Review by boesing — APPROVED** [review]

**Comment by massive** [comment]
Unfortunately this patch seems only to fix the permissions if you happen to monitor /dev/sda. I'm monitoring /dev/sdb, which still gives Operation not permitted even with this patch.

**Comment by McGiverGim** [comment]
@massive true, for this reason I created this other: https://github.com/Draggon/hassio-hdd-tools/pull/19 that let's disable the protection for any other mapping.

**Comment by massive** [comment]
@McGiverGim great. I already created a quick and dirty PR to fix this issue, but seems that you had a better fix in mind. I'll close mine.

**Comment by McGiverGim** [comment]
@massive I don't dislike your solution, it was discussed here: https://github.com/Draggon/hassio-hdd-tools/issues/10 

Both solutions have pros and cons. If the repo was mine I will implement a fusion of both, but is not so it depends on others opinion too.

**Pull request merged**
